### PR TITLE
addRequirement

### PR DESCRIPTION
**Pull request by enesTufekci**
#3

### CODE REVIEW

**Comment by enesTufekci** [comment]
I will make non empty home pr after this merge

**Comment by mxfactorial** [comment]
https://github.com/mxfactorial/requirehub-web/pull/6 already passed https://github.com/mxfactorial/requirehub-web/issues/3 test case.

**Comment by enesTufekci** [comment]
Is there any problem with tests?

**Comment by mxfactorial** [comment]
@enesTufekci Saying this pull request is redundant. This pull request:

screen shot 2018-02-25 at 11 58 36 am

And the https://github.com/mxfactorial/requirehub-web/pull/6 pull request:

screen shot 2018-02-25 at 11 58 24 am

**Pull request closed without merging**
